name: Forex News Discord

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Scarica repository
        uses: actions/checkout@v4

      - name: Installa Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installa librerie
        run: pip install -r requirements.txt

      - name: Invia notizie su Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py
